kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 9092  # Kafka NodePort
        hostPort: 9092
        protocol: TCP
      - containerPort: 2181  # Zookeeper NodePort
        hostPort: 2181
        protocol: TCP
  - role: worker
