configMapGenerator:
  - name: spark-apps
    files:
      - ./spark-apps/analyzer.py
    options:
      disableNameSuffixHash: true

secretGenerator:
  - name: gcs-key
    files:
      - ./secrets/gcs-key.json  # GCS service account key
    options:
      disableNameSuffixHash: true  # Keep the Secret name static
