configMapGenerator:
  - name: spark-apps
    files:
      - ./spark-apps/analyzer.py
    options:
      disableNameSuffixHash: true

secretGenerator:
  - name: gcs-key
    files:
      - ./secrets/gcs-key.json
    options:
      disableNameSuffixHash: true
