apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master
  labels:
    app: spark
    role: master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark
      role: master
  template:
    metadata:
      labels:
        app: spark
        role: master
    spec:
      containers:
        - name: spark-master
          image: docker.io/bitnami/spark:latest
          env:
            - name: SPARK_MODE
              value: "master"
            - name: SPARK_MASTER_PORT
              value: "7077"
          ports:
            - containerPort: 7077 # Spark master port
            - containerPort: 8080 # Spark UI port
          volumeMounts:
            - name: spark-apps
              mountPath: /opt/spark-apps
      volumes:
        - name: spark-apps
          configMap:
            name: spark-apps
---
apiVersion: v1
kind: Service
metadata:
  name: spark-master
spec:
  selector:
    app: spark
    role: master
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30000
    - name: rpc
      port: 7077
      targetPort: 7077
  type: NodePort
