apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-worker
  labels:
    app: spark
    role: worker
spec:
  replicas: 1  # Number of workers to scale based on your workload
  selector:
    matchLabels:
      app: spark
      role: worker
  template:
    metadata:
      labels:
        app: spark
        role: worker
    spec:
      containers:
        - name: spark-worker
          image: docker.io/bitnami/spark:latest
          env:
            - name: SPARK_MODE
              value: "worker"
            - name: SPARK_MASTER_URL
              value: "spark://spark-master:7077"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/opt/secrets/gcs-key.json"
          ports:
            - containerPort: 7077  # Connect to Spark master
            - containerPort: 8081
          volumeMounts:
            - name: gcs-key 
              mountPath: /opt/secrets
              readOnly: true
      volumes:
        - name: gcs-key
          secret:
            secretName: gcs-key
